name: deploy-container

on:
  push:
    branches: # only run this when changes in master branch
      - master
    paths:
      - 'packages/container/**' # only run this when changes in container

defaults:
  run:
    working-directory: packages/container # set execution env to this directory

jobs:
  build:
    runs-on: ubuntu-latest # virtual machine

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-southeast-1